/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
#undef Game_kolumny
#define Game_kolumny 5L
#undef Game_wierszy
#define Game_wierszy 5L
#undef Game_rozmiar
#define Game_rozmiar 25L
/*
 * Class:     Game
 * Method:    nextStep
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Game_nextStep
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
